###not present employee
GET http://localhost:8080/employee/Nick-RnD-QA

###all depatments
GET http://localhost:8080/allDepartments


###employee by fixed id
GET http://localhost:8080/employee

###employees by fixed ids
GET http://localhost:8080/employees

###all employees
GET http://localhost:8080/allEmployees

<> 2025-03-11T164928.200.json

###